import { AreaPage, type AreaConfig } from "./AreaPage";

const area: AreaConfig = {
  city: "Edmond",
  title: "Roofing & Construction Edmond, OK | Redwood Construction Pros",
  description: "Edmond's trusted roofing and construction company. Roof repair, replacement, framing, and new builds. Free estimates from Redwood.",
  canonical: "/areas/edmond",
  intro: "Redwood Construction Pros serves Edmond homeowners and builders with roofing, framing, and construction services built for one of the fastest-growing suburbs in the OKC metro. Edmond is known for top-rated schools, newer neighborhoods, steady development, and homeowners who expect clean work and clear communication. From Coffee Creek and Spring Creek to Deer Creek, Oak Tree, downtown Edmond, and the Gaillardia edge, many homes in Edmond are now 10–25 years old. That age range matters because roofs installed during earlier growth cycles are reaching the point where hail exposure, heat aging, and seal failure need attention. Redwood is local to the metro, understands Edmond's own building permit and inspection process, and does not operate like an out-of-state crew that disappears after storm season. We help Edmond property owners protect newer homes, maintain resale value, and plan structural work with Oklahoma weather and code requirements in mind.",
  roofing: "Roofing in Edmond is shaped by the same hail corridor and high-wind storm paths that affect the rest of the Oklahoma City metro. Redwood provides roof repair for leaks, lifted shingles, flashing failures, missing ridge caps, and damage from tree limbs or wind. For 15–25 year old homes in Edmond neighborhoods, roof replacement may be the better investment when granule loss, brittle shingles, and repeated repairs start adding up. Metal roofing is also gaining interest in Edmond because homeowners planning to stay long term want better heat reflection, longer lifespan, and improved storm performance. After severe weather, we provide storm damage repair, hail damage inspections, photos, and insurance claim support so homeowners can understand whether damage is cosmetic, repairable, or claim-worthy. Edmond homeowners often care about curb appeal and HOA expectations, so Redwood discusses shingle color, material upgrades, ventilation, and cleanup before work begins. The goal is a roof that protects the home and fits the neighborhood.",
  construction: "Edmond's continued growth creates strong demand for residential framing, commercial framing, metal framing, and custom home framing. New additions, garage expansions, outdoor living tie-ins, and remodels are common as families stay in Edmond for schools and want their homes to grow with them. Redwood frames additions and new construction with correct headers, load paths, bracing, and connector hardware. Commercial framing supports retail, office, and service businesses around Edmond's expanding corridors, where tenant improvements need straight walls, schedule control, and inspection-ready details. Metal framing is often the right fit for commercial interiors, fire-rated assemblies, and durable partition layouts. Custom home framing in Edmond often includes open floor plans, engineered beams, tall ceilings, large window openings, and complex rooflines. Redwood reviews plans before lumber or steel is ordered, coordinates with inspectors, and builds framing that supports roofing, mechanicals, drywall, and finishes instead of creating problems for the next trade.",
  why: "Edmond homeowners choose Redwood because the city has a demanding housing market and a mix of newer production homes, luxury properties, and active remodels. A roof problem in Edmond can affect resale value, insurance renewals, and buyer inspections quickly. Many homes are old enough to need roof evaluation but new enough that a smart repair or impact-resistant upgrade can extend value. Edmond's storm exposure means hail, wind, and heat should be considered before selecting materials. The city's separate permit and inspection process also matters for framing, additions, and larger construction scopes. Redwood brings a local contractor voice, transparent estimates, licensed and insured crews, and practical recommendations. We know Edmond is not just another suburb; it is a fast-growing market where homeowners expect the job to be clean, documented, code-aware, and built to last.",
  faqs: [
    { question: "Do many Edmond homes need roof replacement?", answer: "Yes. Many Edmond homes are 10–25 years old, which is the window where hail exposure, heat aging, and shingle wear often require serious roof evaluation." },
    { question: "Does Edmond have its own permit process?", answer: "Yes. Edmond handles building permits and inspections separately from Oklahoma City, and larger roofing or framing scopes may need local review." },
    { question: "What roofing materials work well in Edmond?", answer: "Architectural shingles, Class 4 impact-resistant shingles, and metal roofing are strong options depending on budget, HOA requirements, and long-term plans." },
    { question: "Do you frame additions in Edmond?", answer: "Yes. Redwood frames room additions, garages, outdoor living tie-ins, second-story work, and custom home scopes in Edmond." },
    { question: "Can you help with Edmond hail damage insurance claims?", answer: "Yes. We inspect, document hail damage, meet adjusters when needed, and explain whether filing a claim makes sense based on damage and deductible." },
  ],
};

export default function EdmondAreaPage() { return <AreaPage area={area} />; }
