import { AreaPage, type AreaConfig } from "./AreaPage";

const area: AreaConfig = {
  city: "Midwest City",
  title: "Roofing & Construction Midwest City, OK | Redwood Construction",
  description: "Midwest City OK roofing and construction. Repair, replacement, framing near Tinker AFB. Free estimates from Redwood.",
  canonical: "/areas/midwest-city",
  intro: "Redwood Construction Pros serves Midwest City with roofing, framing, and construction services for a community closely tied to Tinker Air Force Base, Rose State College, and the eastern side of the Oklahoma City metro. Midwest City has a large mix of military and civilian housing, including many 1950s–1970s ranch homes, established neighborhoods near Tinker AFB, homes around the Rose State College area, and newer development toward eastern Midwest City. That housing mix creates practical construction needs: older roofs reaching replacement age, structural framing updates during remodels, fast repair timelines for military relocation, and inspection-ready work for buyers using VA loans. Redwood is local to the metro and understands that Midwest City homeowners often need straight answers quickly. We help property owners repair storm damage, replace worn roofs, frame additions, update older homes, and prepare properties for sale, rental, or inspection without the runaround of an out-of-town contractor.",
  roofing: "Roofing in Midwest City often means working on older roof structures, aging decking, and homes that have seen decades of Oklahoma wind, hail, heat, and ice. Redwood provides roof repair for leaks, missing shingles, flashing problems, pipe boot failures, and storm damage. Many Midwest City ranch homes eventually need roof replacement because asphalt shingles, ventilation, and decking reach the end of service life together. Metal roofing can be a strong upgrade for homeowners who want durability and lower long-term maintenance. After severe weather near Tinker AFB or eastern Midwest City, our storm damage repair and hail damage inspections identify functional damage, document soft metal dents, check attic moisture, and explain whether repairs or replacement make sense. We also provide insurance claim support for covered wind and hail events. Military families and relocating homeowners often need fast, documented roofing work so inspections, closings, and move timelines stay on track. Redwood understands that urgency and communicates clearly.",
  construction: "Framing and construction in Midwest City often involves updating older homes while keeping projects efficient and inspection-ready. Redwood provides residential framing for remodels, room additions, garage conversions, wall reconfiguration, and structural repairs in 1950s–1970s homes. Commercial framing supports local businesses, offices, retail spaces, and service-related properties near Midwest City's main corridors. Metal framing is useful for commercial interiors, fire-rated walls, and durable steel stud assemblies where straight walls and code compliance matter. Custom home framing is available for new builds or major additions that require engineered beams, open floor plans, and roofline coordination. Older Midwest City homes sometimes need framing corrections before finishes can be updated: undersized headers, old roof framing, damaged subfloor, or walls that need proper load support. Redwood links framing decisions to roofing, ventilation, and weather exposure so the finished project is structurally sound, not just cosmetically improved.",
  why: "Midwest City homeowners choose Redwood because the local housing stock creates different needs than a brand-new suburb. Many homes near Tinker AFB and Rose State College are solid but aging, which means roof replacement, roof repair, and structural updates must be handled carefully. Military families often need fast-turnaround work before relocation, sale, rental, or VA inspection deadlines. Older ranch homes may have simple rooflines, but decades of hail, heat, and wind can hide decking and ventilation problems. Redwood offers free estimates, clear documentation, licensed and insured crews, and practical construction recommendations. We understand Midwest City's mix of older homes, military timelines, and eastern metro storm exposure. Whether you need a roof repaired before closing or framing for a remodel, we focus on work that passes inspection and protects the property long after the move-in date.",
  faqs: [
    { question: "Do you work near Tinker Air Force Base?", answer: "Yes. Redwood serves neighborhoods near Tinker AFB, Rose State College, eastern Midwest City, and surrounding eastern OKC metro areas." },
    { question: "Can you help with roofing before a VA loan inspection?", answer: "Yes. We provide roof inspections, repair estimates, documentation, and repair work that can help sellers and buyers address inspection concerns." },
    { question: "Are older Midwest City homes good candidates for re-roofing?", answer: "Many are. Homes from the 1950s–1970s often need roof replacement, ventilation improvements, decking review, or flashing updates." },
    { question: "Do you frame remodels in Midwest City?", answer: "Yes. We frame additions, garage conversions, structural repairs, wall changes, and remodel scopes in older Midwest City homes." },
    { question: "Can Redwood respond quickly for military relocation timelines?", answer: "Yes. We understand that military families often have tight sale, rental, and relocation deadlines, and we communicate schedule options clearly." },
  ],
};

export default function MidwestCityAreaPage() { return <AreaPage area={area} />; }
