import { AreaPage, type AreaConfig } from "./AreaPage";

const area: AreaConfig = {
  city: "Moore",
  title: "Roofing & Construction Moore, OK | Redwood Construction Pros",
  description: "Moore OK roofing and construction contractor. Storm damage experts — roof repair, replacement, framing. Free estimates from Redwood.",
  canonical: "/areas/moore",
  intro: "Redwood Construction Pros serves Moore with roofing, framing, and construction services shaped by one of the most storm-aware communities in Oklahoma. Moore homeowners remember the 2013 EF5 tornado and the 1999 Bridge Creek–Moore tornado, and storm resilience is not an abstract selling point here. It is part of how families think about roofs, framing, safe rooms, storm shelters, and rebuilding. Moore has seen significant new construction and reconstruction after tornado damage, especially around South Moore, Royal Oaks, Moore's east side, and areas near I-35. Redwood is a local metro contractor, not a crew passing through after a weather event. We understand why Moore homeowners ask harder questions about impact-resistant roofing, reinforced framing, connector hardware, and code requirements. Our work is built around practical protection: repair what can be repaired, replace what has failed, and frame structures with Oklahoma wind and inspection requirements in mind.",
  roofing: "Roofing in Moore has to account for hail, wind, tornado-season debris, and the reality that many homeowners have already been through major storm repairs. Redwood provides roof repair for leaks, missing shingles, lifted tabs, flashing failures, punctures, and damage from falling limbs. Roof replacement in Moore often includes discussion of Class 4 impact-resistant shingles, ventilation, decking condition, drip edge, and stronger material options because homeowners want roofs that hold up better after repeated storms. Metal roofing is another strong option for Moore property owners looking for longer lifespan and better heat reflection. After severe weather, our storm damage repair and hail damage inspections include photographs, slope-by-slope documentation, attic checks, and soft metal review. We also provide insurance claim support when storm damage may be covered. Moore homeowners do not need a high-pressure storm chaser; they need a contractor who understands local damage patterns and can explain the right repair path.",
  construction: "Framing and construction in Moore often includes more storm-resilience thinking than in other parts of the metro. Redwood provides residential framing for additions, rebuilds, garages, and new homes; commercial framing for local businesses and tenant improvements; metal framing for durable interior assemblies; and custom home framing for plans that include open layouts, engineered beams, or reinforced details. In Moore, framing conversations often include safe room and storm shelter integration, continuous load paths, anchor points, hold-downs, hurricane ties, and connection hardware. Moore building codes and inspection expectations were strengthened after major tornado events, and Redwood builds with those requirements in mind. Many projects near I-35, South Moore, and the east side involve tying new construction into existing homes or rebuilding portions of storm-affected structures. We review plans, identify structural concerns, and coordinate framing with the roof system because wind resistance depends on how the whole structure is connected.",
  why: "Moore homeowners choose Redwood because this city has a specific history with severe weather, rebuilding, and construction standards. A roof in Moore is not just curb appeal; it is the first line of defense against hail, wind, and water. Framing is not just lumber; it is the structure that ties the home together during Oklahoma storms. Many Moore homes have been repaired, rebuilt, expanded, or upgraded after tornado events, and homeowners often want stronger materials and clearer documentation. Redwood offers free estimates, licensed and insured crews, transparent pricing, and direct explanations. We understand Moore's concern with storm resilience, impact-rated roofing, reinforced framing, and inspection-ready work. Whether the property is in Royal Oaks, South Moore, near I-35, or on Moore's east side, Redwood treats weather risk as a central part of the project scope.",
  faqs: [
    { question: "Do Moore homeowners need impact-resistant roofing?", answer: "Impact-resistant shingles are not mandatory for every home, but many Moore homeowners choose Class 4 materials because hail and storm exposure are frequent." },
    { question: "Can Redwood integrate safe rooms or storm shelters with framing?", answer: "Yes. We can coordinate framing around safe room and storm shelter plans, engineered details, and required structural connections." },
    { question: "Did Moore building codes change after tornadoes?", answer: "Moore strengthened building requirements after major tornado events, and structural details, connectors, and inspections matter on framing and construction scopes." },
    { question: "Do you provide emergency storm damage roof repair in Moore?", answer: "Yes. Redwood provides storm inspections, tarping when needed, roof repair, replacement, and insurance documentation in Moore." },
    { question: "Can you help with Moore roof insurance claims?", answer: "Yes. We document hail, wind, and storm damage, meet adjusters when needed, and explain repair versus replacement options." },
  ],
};

export default function MooreAreaPage() { return <AreaPage area={area} />; }
