import { AreaPage, type AreaConfig } from "./AreaPage";

const area: AreaConfig = {
  city: "Norman",
  title: "Roofing & Construction Norman, OK | Redwood Construction Pros",
  description: "Norman OK roofing and construction — repair, replacement, framing, custom builds. Home of OU. Free estimates from Redwood.",
  canonical: "/areas/norman",
  intro: "Redwood Construction Pros serves Norman with roofing, framing, and construction services for a city that has a different rhythm than the rest of the metro. Norman is home to the University of Oklahoma, which means the housing market includes historic homes near campus, student rentals, investor-owned properties, family neighborhoods, and fast-growing developments on the east and south sides. Around Campus Corner, older homes often need careful roof repairs, flashing work, and framing tie-ins during remodels. In Brookhaven, The Trails, Legacy Trail, and newer east side developments, homeowners may be planning roof replacement, additions, or custom framing scopes. Redwood is local to the OKC metro and understands that Norman has its own code enforcement, permit requirements, and inspection process. We help owner-occupants, landlords, builders, and property managers protect structures that have to survive Oklahoma storms and still pass buyer, tenant, or lender scrutiny.",
  roofing: "Roofing in Norman ranges from historic home repair near OU to roof replacement on newer subdivisions and rental property maintenance near student housing corridors. Redwood provides roof repair for leaks, missing shingles, pipe boot failures, chimney flashing, and storm-related damage. When an older roof is beyond repair, roof replacement includes tear-off, deck inspection, ventilation review, new underlayment, flashing, and material options suited for Norman's weather. Metal roofing is a good upgrade for property owners who want long service life and lower maintenance, especially on rentals, shops, and homes exposed to repeated hail. Norman storms bring hail, wind, driven rain, and falling limbs, so our storm damage repair and hail damage inspections document visible and hidden damage before more water enters the home. We also provide insurance claim support for landlords and homeowners who need organized photos, measurements, and repair scope information. Redwood helps Norman property owners decide what is urgent, what is maintenance, and what deserves a claim.",
  construction: "Framing and construction in Norman are driven by both growth and reinvestment. East Norman and south Norman developments need residential framing for new homes, additions, garages, and custom builds, while older campus-area properties often need remodel framing, structural repair, and careful tie-ins to existing rooflines. Redwood provides residential framing for new construction and additions, commercial framing for offices, retail, restaurants, and service businesses, metal framing for steel stud interiors and rated assemblies, and custom home framing for complex designs. Norman's code enforcement and permit requirements are separate from OKC, so plan review, inspection coordination, and structural details matter. Rental property owners also need work completed efficiently because downtime affects occupancy. Redwood frames walls, openings, headers, roof structures, and bracing with Oklahoma wind loads and inspection expectations in mind. Whether the job is a landlord repair, a family addition in Brookhaven, or a new build near the east side, we build structure first and finishes second.",
  why: "Norman homeowners choose Redwood because the city blends university housing, historic neighborhoods, family suburbs, and active new construction. That mix requires a contractor who can handle more than one type of project. A landlord may need fast roof repair before the next tenant move-in, while a homeowner near The Trails may be comparing impact-resistant shingles after hail damage. A custom build in south Norman may need precise framing, engineered beams, and roofline coordination. Norman's weather is the same severe Oklahoma pattern — hail in spring, high winds, heavy rain, and summer heat — but the property needs vary by neighborhood. Redwood offers free estimates, straight explanations, and local construction knowledge. We understand the difference between preserving an older home, protecting a rental property, and framing a new project that needs to pass inspection without delays.",
  faqs: [
    { question: "Do you work on rental property roofs in Norman?", answer: "Yes. Redwood helps Norman landlords with roof repair, replacement, storm inspections, and documentation needed to protect rental properties." },
    { question: "Does Norman have separate permit requirements?", answer: "Yes. Norman has its own code enforcement and permitting process for building and structural work, separate from Oklahoma City." },
    { question: "What roof problems are common near OU campus?", answer: "Older homes near campus often have flashing issues, aging shingles, old decking, ventilation problems, and repair needs from deferred maintenance." },
    { question: "Do you provide framing for new construction in Norman?", answer: "Yes. We frame new homes, additions, garages, commercial interiors, and custom homes in Norman and nearby growth areas." },
    { question: "Can Redwood help after Norman hail storms?", answer: "Yes. We provide hail inspections, storm damage repair, insurance documentation, and replacement options when damage is widespread." },
  ],
};

export default function NormanAreaPage() { return <AreaPage area={area} />; }
