import { AreaPage, type AreaConfig } from "./AreaPage";

const area: AreaConfig = {
  city: "Oklahoma City",
  title: "Roofing & Construction Oklahoma City | Redwood Construction Pros",
  description: "Trusted roofing and construction in Oklahoma City. Roof repair, replacement, framing, custom homes. Free estimates. Call Redwood.",
  canonical: "/areas/oklahoma-city",
  intro: "Redwood Construction Pros serves Oklahoma City as a local roofing and construction partner, not a fly-by-night storm crew chasing hail from another state. OKC is the state capital and largest city in Oklahoma, with housing that changes block by block: 1920s bungalows in Gatewood and Heritage Hills, historic homes near Mesta Park and Paseo, infill work around Midtown and Deep Deuce, established properties around Lake Hefner, and new construction pushing toward the Edmond border and Deer Creek. That mix requires a contractor who understands old roof decking, modern framing requirements, permit expectations, and Oklahoma weather. Oklahoma City roofs take more punishment than almost anywhere in the country because the metro sits in the heart of Tornado Alley. Redwood helps homeowners in Nichols Hills, Capitol Hill, SW Oklahoma City, and far north OKC make smart decisions about repairs, replacement, framing, and construction.",
  roofing: "Roofing in Oklahoma City has to be built around hail, wind, heat, and sudden weather changes. Redwood provides roof repair for leaks, missing shingles, failed flashing, and small storm issues before they spread into decking and interiors. When a roof is aged out or damage covers multiple slopes, we provide roof replacement with full tear-off, deck inspection, underlayment, flashing, ventilation, and premium materials. For homeowners who want longer service life, metal roofing is a strong choice around Oklahoma City because it handles heat, wind, and repeated storms better than standard asphalt. After spring storms, our storm damage repair and hail damage inspections include photos, slope-by-slope findings, soft metal checks, and attic review. We also provide insurance claim support when wind or hail damage may be covered. From a bungalow in Gatewood to a commercial property near I-40, Redwood inspects the whole roof system instead of selling a one-size-fits-all repair.",
  construction: "Redwood also provides framing and construction services across Oklahoma City for homeowners, builders, and property owners who need structural work done correctly. Residential framing includes additions, garages, remodel tie-ins, new home framing, floor systems, wall framing, roof framing, and structural sheathing. Commercial framing supports tenant improvements, offices, retail spaces, restaurants, and multi-family scopes where schedules and code details matter. For commercial interiors and fire-rated wall assemblies, metal framing offers straight walls, termite resistance, and durable steel stud construction. Custom home framing is especially important in OKC infill and north metro builds where open floor plans, large window openings, LVL beams, and complex rooflines require careful plan review. Oklahoma City building permits and inspections expect correct bracing, fasteners, load path connections, and structural details. Redwood frames with the inspector, roofing system, and finished structure in mind, which reduces rework and helps the project move cleanly into rough-ins and finishes.",
  why: "Oklahoma City homeowners choose Redwood because we understand the city's wide range of homes and the local building environment. A 1920s home in Heritage Hills may need careful roof repair around old decking and masonry flashing, while a newer Deer Creek home may be hitting the first major roof replacement window after 15–20 years of hail exposure. Properties near Lake Hefner deal with wind exposure, while Midtown and Deep Deuce remodels often require framing that ties new construction into older structures. Oklahoma City's growth keeps permit offices, inspectors, and construction schedules busy, so homeowners need a contractor who can communicate clearly and prepare work correctly. Redwood offers free estimates, transparent pricing, licensed and insured crews, and practical recommendations. We know when repair is enough, when replacement is smarter, and when framing details need engineered attention before finishes cover them up.",
  faqs: [
    { question: "How much does roofing cost in Oklahoma City?", answer: "Roof repairs in Oklahoma City often range from $300–$1,500, while full asphalt roof replacement on many homes runs $8,000–$15,000 depending on size, pitch, decking, and materials." },
    { question: "What roof types are common in Oklahoma City?", answer: "Architectural asphalt shingles are most common, but metal roofing and Class 4 impact-resistant shingles are increasingly popular because of hail and wind exposure." },
    { question: "Do Oklahoma City building codes affect roofing and framing?", answer: "Yes. Permits, inspections, wind bracing, roof ventilation, decking, flashing, and structural connection details can all affect the final scope." },
    { question: "How should I prepare my OKC roof for storm season?", answer: "Schedule an inspection before spring, clear gutters, trim limbs, check attic leaks, and document roof condition before severe weather arrives." },
    { question: "Can Redwood act as a general contractor in Oklahoma City?", answer: "Redwood can coordinate roofing, framing, and construction scopes and work with owners, builders, architects, and inspectors depending on project needs." },
  ],
};

export default function OklahomaCityAreaPage() { return <AreaPage area={area} />; }
